### ISSUE TITLE
Usage of :wx in dependencies

### ISSUE THREAD

**Issue by lukeses** [Kociamber/ex_owm#21]
Hi @Kociamber!

Thank you for a nice wrapper library around Open Weather API!

I have a question is there a real need for a :wx dependency (https://www.erlang.org/doc/apps/wx/wx.html) in this library?

It is listed in:
```
  def application do
    [
      extra_applications: [:logger, :wx, :observer, :runtime_tools],
      mod: {ExOwm.Application, []}
    ]
  end
```

While releasing an application, I was getting an error:
```
#26 [builder 20/20] RUN mix release
#26 0.918 ** (Mix) Could not find application :wx
```

While not getting an error around: `:observer`, it seems to me that, it could be also removed together with `:wx`.

I may make a PR, if you're open for removing it.

**Comment by Kociamber** [comment]
Hi and thank you! Let me have a look, it might not be necessary in the end.

**Comment by Kociamber** [comment]
@lukeses I just had a quick look. I did try to reproduce your error but I had no issues with the release. However, both `:wx` and `:observer` are not really necessary here, I will remove them both now. 

Please let me know if the change will help.

**Comment by Kociamber** [comment]
Closing the issue for now, please let me know if you encounter more problems.
